### PR TITLE
License as LGPL v2

### PR DESCRIPTION
**Pull request by xjuan**
Hello guys, I am trying to relicense this project as LGPL so that it can be used by lgpl libraries.

I already contacted Rob (@ramcq) from Endless Foundation (@endlessm) and he agrees with releasing the original work done by Jasper as LGPL.

@alexlarsson @jadahl  Would you like to release your contributions too?

thanks

Juan Pablo

### CODE REVIEW

**Comment by ramcq** [comment]
You can update the copyright to Endless OS Foundation LLC as well. :)

**Comment by jadahl** [comment]
Switching to LGPL seems like a good idea, so fine by me.

**Comment by alexlarsson** [comment]
I’m fine with relicensing to lgpl.

**Comment by ramcq** [comment]
I approve too, Alex if you maybe merge the PR then you/Juan can import it into GNOME? I think GitLab has a way to just pull a whole repo over with its issues/PRs/etc.

**Pull request merged**
